# Generated by Django 5.1.6 on 2025-03-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='colors',
        ),
    ]
